//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Addressid { get; set; }
        public string Addressname { get; set; }
        public string Addresssuozaidiqu { get; set; }
        public string Addressxiangxidiqu { get; set; }
        public string Addressyoubian { get; set; }
        public string Addressphone { get; set; }
        public Nullable<int> Userxixids { get; set; }
        public string Addressstaus { get; set; }
    
        public virtual Userxix Userxix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
