//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Adminid { get; set; }
        public string Adminname { get; set; }
        public string Adminmima { get; set; }
        public Nullable<int> Userxixid { get; set; }
    
        public virtual Userxix Userxix { get; set; }
    }
}
