//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect
    {
        public int Collectid { get; set; }
        public int Goodid { get; set; }
        public System.DateTime Collectdate { get; set; }
        public int Userxixid { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Userxix Userxix { get; set; }
    }
}
