//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goodtypetwo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goodtypetwo()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Goodtypetwoid { get; set; }
        public string Goodtypetwoname { get; set; }
        public Nullable<int> Goodtypeoneid { get; set; }
        public Nullable<int> Goodid { get; set; }
        public string Goodtypetwostatus { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Goodtypeone Goodtypeone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
