//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foodEntities : DbContext
    {
        public foodEntities()
            : base("name=foodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<footprint> footprint { get; set; }
        public virtual DbSet<Good> Good { get; set; }
        public virtual DbSet<Goodkowei> Goodkowei { get; set; }
        public virtual DbSet<Goodtypeone> Goodtypeone { get; set; }
        public virtual DbSet<Goodtypetwo> Goodtypetwo { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Ordertuihuo> Ordertuihuo { get; set; }
        public virtual DbSet<Param> Param { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<shopping> shopping { get; set; }
        public virtual DbSet<Userxix> Userxix { get; set; }
    }
}
