//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordertuihuo
    {
        public int Ordertuihuoid { get; set; }
        public int Goodid { get; set; }
        public string Ordertuihuomoneys { get; set; }
        public string Ordertuihuostatus { get; set; }
        public Nullable<System.DateTime> Ordertuihuodate { get; set; }
        public Nullable<int> Orderid { get; set; }
        public string Ordertuihuoyuangyi { get; set; }
        public string OrdertuihuoImage { get; set; }
        public string Ordertuihuotype { get; set; }
        public string Ordertuihuoshuomin { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Order Order { get; set; }
    }
}
