//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Ordertuihuo = new HashSet<Ordertuihuo>();
            this.Score = new HashSet<Score>();
        }
    
        public int Orderid { get; set; }
        public string Ordername { get; set; }
        public string Ordernum { get; set; }
        public string Ordersum { get; set; }
        public Nullable<int> Goodid { get; set; }
        public Nullable<System.DateTime> Ordertime { get; set; }
        public string Orderwuliu { get; set; }
        public Nullable<int> Goodtypetwoid { get; set; }
        public string Orderstatus { get; set; }
        public string Orderzt { get; set; }
        public Nullable<int> Addressid { get; set; }
        public string Ordertixifahuo { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Good Good { get; set; }
        public virtual Goodtypetwo Goodtypetwo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordertuihuo> Ordertuihuo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
    }
}
