//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param
    {
        public int Paramid { get; set; }
        public string ParamProductionid { get; set; }
        public string Parammethod { get; set; }
        public string Paramdate { get; set; }
        public string Paramedible { get; set; }
        public string Paramcontent { get; set; }
        public string Paramproduct { get; set; }
        public string Paramstandard { get; set; }
        public string Paramsite { get; set; }
        public Nullable<int> Goodid { get; set; }
        public string Goodimage1 { get; set; }
        public string Goodimage2 { get; set; }
        public string Goodimage3 { get; set; }
        public string Goodimage4 { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
