//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping
    {
        public int shoppingid { get; set; }
        public Nullable<int> Goodid { get; set; }
        public Nullable<int> shoppingnum { get; set; }
        public Nullable<System.DateTime> shoppingdate { get; set; }
        public string shoppingmoney { get; set; }
        public Nullable<int> Userxixid { get; set; }
        public string shoppcheck { get; set; }
        public Nullable<int> Goodkoweiid { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Goodkowei Goodkowei { get; set; }
        public virtual Userxix Userxix { get; set; }
    }
}
