//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userxix
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userxix()
        {
            this.Address = new HashSet<Address>();
            this.Admin = new HashSet<Admin>();
            this.Collect = new HashSet<Collect>();
            this.footprint = new HashSet<footprint>();
            this.Score = new HashSet<Score>();
            this.shopping = new HashSet<shopping>();
        }
    
        public int Userxixid { get; set; }
        public string Userxixnich { get; set; }
        public string Userxixname { get; set; }
        public string Userxixgender { get; set; }
        public Nullable<System.DateTime> Userxixbirthday { get; set; }
        public string Userxixphone { get; set; }
        public string Userxixemail { get; set; }
        public string Usermima { get; set; }
        public string Userstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collect> Collect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<footprint> footprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shopping> shopping { get; set; }
    }
}
